name: pytest

on: [push, pull_request]

jobs:
  run_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Apply database migrations (if applicable)
      run: |
        python manage.py migrate

    - name: Run Django Server
      run: |
        python manage.py runserver

    - name: Wait for Django Server to start
      run: |
        echo "Waiting for Django server to start..."
        sleep 10  # You may need to adjust the sleep time based on your application's startup time.

    - name: Run pytest
      run: |
        pytest