name: PyTests

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: your_database_name
          POSTGRES_USER: your_username
          POSTGRES_PASSWORD: your_password

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Apply database migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        pytest